### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by mohdaaqib** [Galustom/Group7#2]
[projectStructure-eps-converted-to.pdf](https://github.com/Galustom/Group7/files/2419740/projectStructure-eps-converted-to.pdf)

**Comment by szattila98** [comment]
I think its done, close the issue if its OK, please.

**Comment by mohdaaqib** [comment]
Some issues that has to be fixed at first glance

- src folder is not necessary in bundle
- Dummy App and AppTest files will have to be removed when you add real classes and test to the project.

**Comment by szattila98** [comment]
I deleted the src folder from bundle, the dummy files will be removed when other files are added because github doesnt like empty folders apparently.
