### ISSUE TITLE
Dao and file handling

### ISSUE THREAD

**Issue by szattila98** [Galustom/Group7#7]
You (@vrobert938 and @nestling04 ) will have to desing the dao module for our project. We already decided that we will use XML files for data storage. The basic methods you should implement are in the BookDaoInteface class (added by me @szattila98 ) in the service module. Further details will be added as comments to this issue.

**Comment by vrobert938** [comment]
We need to discuss about what kind of data we need to return from DAO?

We need to define where the DAO ends and where the SERVICES starts? What kind of model do you need? 
example: 
Thats will be ok if we return with List<book> or List<borrowing>?

**Comment by szattila98** [comment]
The return types are already defined in service/src/main/java/hu/iit/uni/miskolc/swtest/dao/BookDaoInterface.java (which you should implement).
The readBooks() methods return type is a Collection of Book, so yeah, it can be a List.
The return type of the other methods in there is set to void, but it can be changed if a design choice demands it.

**Comment by nestling04** [comment]
I think this issue could be closed, the implementation of dao is done. @szattila98 please feel free to close this issue if you think the same, or tell us what else to do.

**Comment by szattila98** [comment]
I feel that you have done your part regarding this issue, so consider it done.
